CREATE TABLE TB_USER(
    USER_NM VARCHAR2(30) NOT NULL ,
    USER_ID VARCHAR2 (30) PRIMARY KEY,
    USER_PW VARCHAR2 (30) NOT NULL
);

SELECT * FROM TB_USER;
select user_id from tb_user where user_id = 'akdlwb1212';
DROP TABLE TB_USER;


CREATE TABLE TB_SAVEP(
    USER_ID VARCHAR2 (30),
    USER_SP VARCHAR2 (200),
    CONSTRAINT SAVEP_FK FOREIGN KEY(USER_ID) REFERENCES TB_USER(USER_ID)
);

DROP TABLE TB_SAVEP;

SELECT * FROM TB_SAVEP;
select * from 회원가입;

